services:
  - type: web
    name: fleetGuard-back
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_DATASOURCE_CONNECTION_STRING
        fromDatabase:
          name: elephant
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: elephant
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: elephant
          property: password
      - key: SPRING_DATASOURCE_HOST
        fromDatabase:
          name: elephant
          property: host
      - key: SPRING_DATASOURCE_PORT
        fromDatabase:
          name: elephant
          property: port
      - key: SPRING_DATASOURCE_SCHEMA
        fromDatabase:
          name: elephant
          property: database
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_SCHEMA}
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: elephant
    plan: free
